# use https://docs.travis-ci.com/user/languages/javascript-with-nodejs/ Travis build image
language: node_js
node_js:
  - 15

services:
  - docker

script:
  # Install insomnia-inso (Inso CLI) which is needed by our Maven build process later
  - npm install insomnia-inso
  - inso --version
  - node_modules/insomnia-inso/bin/inso --version

  # Install Java & Maven with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 15.0.1.hs-adpt
  - sdk install maven

  # Build Spring Boot app with Maven
  # This also generates OpenAPI spec file at weatherbackend/target/openapi.json
  # and the Kong declarative config at kong/kong.yml from the OpenAPI spec with Inso CLI
  - mvn clean verify --file weatherbackend/pom.xml --no-transfer-progress -Dinso.executable.path=node_modules/insomnia-inso/bin/inso

  # Show kong.yml
  - cat kong/kong.yml

  # Fire Up Docker Compose setup with Kong
  - docker-compose up -d
  - docker ps -a

  # Let's wait until Kong is available (we need to improve this)
  # see https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
  # and https://stackoverflow.com/questions/43918874/how-to-increase-no-activity-wait-time-in-travis-ci
  - travis_wait 1

  # Also have a look into the Kong logs
  - docker ps -a
  - docker-compose logs kong

  # Verify that we can call our Spring Boot service through Kong
  - curl http://localhost:8000/weather/MaxTheKongUser

